#!/bin/sh

# /dev/null is just a file of 0's
# Basically clearing the results file
cat /dev/null >  results

TIMEFORMAT=%E

for sort in Bubble Insertion Selection Merge Quick Shell
do
  case $sort in
    Bubble) flag=0 ;;
    Insertion) flag=1 ;;
    Selection) flag=2 ;;
    Merge) flag=3 ;;
    Quick) flag=4 ;;
    Shell) flag=5 ;;
  esac

  cat /dev/null > ${sort}Desc

  for i in 1000 2000 4000 # 8000 16000 32000 64000
  do
    avg=0
    for p in 1 2 3 4 5
    do
      t=$( { ./num_gen.py $i D | (time ./sorts $flag $i) > /dev/null; } 2>&1)
      avg=`echo "$t + $avg" | bc -l`
    done;
    avg=`echo "$avg / 5" | bc -l`
    echo "Average for N=$i is: $avg" >> ${sort}Desc
  done;
done;

wait;
echo "Done!";
